CREATE TABLE public.admin (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255),
    password character varying(255),
    name character varying(255),
    role character varying(255),
    avatar character varying(255),
    password_version integer DEFAULT 1 NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

CREATE TABLE public.category (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    description character varying(200),
    sort_order integer DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT chk_category_status CHECK (
        status::text = ANY (ARRAY['visible'::character varying::text, 'hidden'::character varying::text])
    ),
    CONSTRAINT uk_category_name UNIQUE (name)
);

CREATE TABLE public.tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT tag_pkey PRIMARY KEY (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

CREATE TABLE public.article (
    id bigint GENERATED ALWAYS AS IDENTITY,
    category_id bigint,
    title character varying(120) NOT NULL,
    summary character varying(300),
    content text NOT NULL,
    cover_url character varying(500),
    status character varying(20) NOT NULL,
    is_top boolean DEFAULT false NOT NULL,
    is_recommend boolean DEFAULT false NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    comment_count integer DEFAULT 0 NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    like_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT article_pkey PRIMARY KEY (id),
    CONSTRAINT fk_article_category FOREIGN KEY (category_id)
        REFERENCES public.category(id) ON DELETE RESTRICT
);

ALTER TABLE public.article
    ADD CONSTRAINT article_status_check
    CHECK (
        status::text = ANY (
            ARRAY[
                'draft'::character varying::text,
                'published'::character varying::text,
                'hidden'::character varying::text
            ]
        )
    ) NOT VALID;

CREATE TABLE public.article_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    article_id bigint NOT NULL,
    visitor_key_hash character(64) NOT NULL,
    ip_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT article_like_pkey PRIMARY KEY (id),
    CONSTRAINT article_like_article_id_fkey FOREIGN KEY (article_id)
        REFERENCES public.article(id) ON DELETE CASCADE
);

CREATE TABLE public.article_tag (
    article_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    CONSTRAINT uk_article_tag_article_id_tag_id UNIQUE (article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id)
        REFERENCES public.article(id) ON DELETE CASCADE,
    CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id)
        REFERENCES public.tag(id) ON DELETE CASCADE
);

CREATE TABLE public.blog_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email character varying(320) NOT NULL,
    password character varying(255) NOT NULL,
    nickname character varying(50) NOT NULL,
    avatar character varying(500),
    status character varying(20) DEFAULT 'enabled'::character varying NOT NULL,
    password_version integer DEFAULT 1 NOT NULL,
    delete_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT blog_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_blog_user_email UNIQUE (email),
    CONSTRAINT ck_blog_user_status CHECK (
        status::text = ANY (
            ARRAY[
                'enabled'::character varying::text,
                'disabled'::character varying::text,
                'pending_deletion'::character varying::text
            ]
        )
    ),
    CONSTRAINT ck_blog_user_delete_at CHECK (
        status::text = 'pending_deletion'::text AND delete_at IS NOT NULL
        OR status::text = ANY (
            ARRAY['enabled'::character varying::text, 'disabled'::character varying::text]
        ) AND delete_at IS NULL
    )
);

CREATE SEQUENCE public.music_id_seq AS bigint;

CREATE TABLE public.music (
    id bigint DEFAULT nextval('public.music_id_seq'::regclass) NOT NULL,
    title character varying(120) NOT NULL,
    artist character varying(120),
    audio_url character varying(500) NOT NULL,
    duration_ms integer NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pk_music PRIMARY KEY (id),
    CONSTRAINT uq_music_audio_url UNIQUE (audio_url),
    CONSTRAINT ck_music_duration_positive CHECK (duration_ms > 0)
);

ALTER SEQUENCE public.music_id_seq OWNED BY public.music.id;

CREATE TABLE public.site_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    background_url character varying(500),
    CONSTRAINT site_config_pkey PRIMARY KEY (id)
);

INSERT INTO public.site_config (background_url) VALUES (NULL);

CREATE INDEX idx_article_category_list_sort
    ON public.article (
        category_id,
        is_top DESC,
        published_at DESC NULLS LAST,
        created_at DESC,
        id DESC
    );

CREATE INDEX idx_article_list_sort
    ON public.article (
        is_top DESC,
        published_at DESC NULLS LAST,
        created_at DESC,
        id DESC
    );

CREATE INDEX idx_article_status_list_sort
    ON public.article (
        status,
        is_top DESC,
        published_at DESC NULLS LAST,
        created_at DESC,
        id DESC
    );

CREATE INDEX idx_article_like_ip_created_at
    ON public.article_like (ip_hash, created_at DESC);

CREATE UNIQUE INDEX uk_article_like_article_visitor
    ON public.article_like (article_id, visitor_key_hash);

CREATE INDEX idx_article_tag_tag_id_article_id
    ON public.article_tag (tag_id, article_id);

CREATE INDEX ix_music_created_id
    ON public.music (created_at, id);

COMMENT ON COLUMN public.admin.id IS '主键';
COMMENT ON COLUMN public.admin.username IS '用户名';
COMMENT ON COLUMN public.admin.password IS '密码';
COMMENT ON COLUMN public.admin.name IS '管理员名称';
COMMENT ON COLUMN public.admin.role IS '角色';
COMMENT ON COLUMN public.admin.avatar IS '管理员头像';
COMMENT ON COLUMN public.admin.password_version IS '管理员密码版本号';
COMMENT ON CONSTRAINT id ON public.admin IS '主键';

COMMENT ON COLUMN public.article.id IS E'文章id\n';
COMMENT ON COLUMN public.article.category_id IS '文章分类ID，可为空，关联category.id';
COMMENT ON COLUMN public.article.title IS '文章标题';
COMMENT ON COLUMN public.article.summary IS '文章摘要';
COMMENT ON COLUMN public.article.content IS '文章正文';
COMMENT ON COLUMN public.article.cover_url IS '文章封面图片';
COMMENT ON COLUMN public.article.status IS '文章状态';
COMMENT ON COLUMN public.article.is_top IS '是否置顶';
COMMENT ON COLUMN public.article.is_recommend IS '是否推荐';
COMMENT ON COLUMN public.article.view_count IS '阅读数量';
COMMENT ON COLUMN public.article.comment_count IS '评论数量';
COMMENT ON COLUMN public.article.published_at IS '发布时间';
COMMENT ON COLUMN public.article.created_at IS '创建时间';
COMMENT ON COLUMN public.article.updated_at IS '更新时间';

COMMENT ON TABLE public.article_tag IS '文章标签关联表，一条记录表示一篇文章绑定一个标签';
COMMENT ON COLUMN public.article_tag.article_id IS '文章ID，关联article.id';
COMMENT ON COLUMN public.article_tag.tag_id IS '标签ID，关联tag.id';

COMMENT ON TABLE public.blog_user IS '博客用户表，保存已完成邮箱验证的正式用户账号。';
COMMENT ON COLUMN public.blog_user.id IS '用户主键，永久业务身份，供其他业务表关联。';
COMMENT ON COLUMN public.blog_user.email IS '登录邮箱；应用保存前统一去除首尾空格并转为小写。';
COMMENT ON COLUMN public.blog_user.password IS '密码哈希，禁止保存明文密码。';
COMMENT ON COLUMN public.blog_user.nickname IS '用户展示昵称，可重复。';
COMMENT ON COLUMN public.blog_user.avatar IS '头像地址或文件标识，可为空。';
COMMENT ON COLUMN public.blog_user.status IS '账号状态：enabled、disabled 或 pending_deletion。';
COMMENT ON COLUMN public.blog_user.password_version IS '密码版本号；修改或重置密码后递增，使旧 Token 失效。';
COMMENT ON COLUMN public.blog_user.delete_at IS '待删除账号的物理删除时间；仅 pending_deletion 状态使用。';
COMMENT ON COLUMN public.blog_user.created_at IS '用户创建时间。';
COMMENT ON COLUMN public.blog_user.updated_at IS '用户最后修改时间。';

COMMENT ON TABLE public.category IS '文章分类表';
COMMENT ON COLUMN public.category.id IS '分类主键ID';
COMMENT ON COLUMN public.category.name IS '分类名称，唯一';
COMMENT ON COLUMN public.category.description IS '分类描述';
COMMENT ON COLUMN public.category.sort_order IS '分类排序值，数值越小越靠前';
COMMENT ON COLUMN public.category.status IS '分类状态，可选值：visible、hidden';
COMMENT ON COLUMN public.category.created_at IS '分类创建时间';
COMMENT ON COLUMN public.category.updated_at IS '分类更新时间';

COMMENT ON TABLE public.music IS '音乐表：管理员上传的本地 MP3 及基础业务信息';
COMMENT ON COLUMN public.music.id IS '音乐 ID';
COMMENT ON COLUMN public.music.title IS '歌曲名';
COMMENT ON COLUMN public.music.artist IS '歌手';
COMMENT ON COLUMN public.music.audio_url IS '文件模块返回的 MP3 地址';
COMMENT ON COLUMN public.music.duration_ms IS 'Mutagen 解析出的毫秒时长';
COMMENT ON COLUMN public.music.is_enabled IS '是否出现在访客列表';
COMMENT ON COLUMN public.music.created_at IS '创建时间';
COMMENT ON COLUMN public.music.updated_at IS '最后修改时间';

COMMENT ON TABLE public.tag IS '文章标签表';
COMMENT ON COLUMN public.tag.id IS '标签主键ID';
COMMENT ON COLUMN public.tag.name IS '标签名称，唯一';
COMMENT ON COLUMN public.tag.created_at IS '标签创建时间';
COMMENT ON COLUMN public.tag.updated_at IS '标签更新时间';

INSERT INTO public.admin (username, password, name, role, avatar, password_version)
VALUES (
    'admin',
    '$2a$12$J1gu8Jl6mjWU5MBR7EoQuemsC2JO6BhXFqF5cwDJUoNDL4kqVd12S',
    'admin',
    'admin',
    NULL,
    1
);
