--
-- PostgreSQL database dump
--

\restrict 9WQwNmSj2qUgLjFjHk5gKJhIT4hnWGjCoFFyuC9Q7rDLhXko4VUOJFr1ItomIjQ

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: public; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin (
    id integer NOT NULL,
    username character varying(255),
    password character varying(255),
    name character varying(255),
    role character varying(255),
    avatar character varying(255),
    password_version integer DEFAULT 1 NOT NULL
);


--
-- Name: COLUMN admin.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.id IS '主键';


--
-- Name: COLUMN admin.username; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.username IS '用户名';


--
-- Name: COLUMN admin.password; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.password IS '密码';


--
-- Name: COLUMN admin.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.name IS '管理员名称';


--
-- Name: COLUMN admin.role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.role IS '角色';


--
-- Name: COLUMN admin.avatar; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.avatar IS '管理员头像';


--
-- Name: COLUMN admin.password_version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.admin.password_version IS '管理员密码版本号';


--
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article (
    id bigint NOT NULL,
    category_id bigint,
    title character varying(120) NOT NULL,
    summary character varying(300),
    content text NOT NULL,
    cover_url character varying(500),
    status character varying(20) NOT NULL,
    is_top boolean DEFAULT false NOT NULL,
    is_recommend boolean DEFAULT false NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    comment_count integer DEFAULT 0 NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    like_count integer DEFAULT 0 NOT NULL
);


--
-- Name: COLUMN article.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.id IS '文章id
';


--
-- Name: COLUMN article.category_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.category_id IS '文章分类ID，可为空，关联category.id';


--
-- Name: COLUMN article.title; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.title IS '文章标题';


--
-- Name: COLUMN article.summary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.summary IS '文章摘要';


--
-- Name: COLUMN article.content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.content IS '文章正文';


--
-- Name: COLUMN article.cover_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.cover_url IS '文章封面图片';


--
-- Name: COLUMN article.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.status IS '文章状态';


--
-- Name: COLUMN article.is_top; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.is_top IS '是否置顶';


--
-- Name: COLUMN article.is_recommend; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.is_recommend IS '是否推荐';


--
-- Name: COLUMN article.view_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.view_count IS '阅读数量';


--
-- Name: COLUMN article.comment_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.comment_count IS '评论数量';


--
-- Name: COLUMN article.published_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.published_at IS '发布时间';


--
-- Name: COLUMN article.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.created_at IS '创建时间';


--
-- Name: COLUMN article.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article.updated_at IS '更新时间';


--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_like (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    visitor_key_hash character(64) NOT NULL,
    ip_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: article_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_tag (
    article_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: TABLE article_tag; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.article_tag IS '文章标签关联表，一条记录表示一篇文章绑定一个标签';


--
-- Name: COLUMN article_tag.article_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article_tag.article_id IS '文章ID，关联article.id';


--
-- Name: COLUMN article_tag.tag_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.article_tag.tag_id IS '标签ID，关联tag.id';


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(200),
    sort_order integer DEFAULT 0 NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_category_status CHECK (((status)::text = ANY ((ARRAY['visible'::character varying, 'hidden'::character varying])::text[])))
);


--
-- Name: TABLE category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.category IS '文章分类表';


--
-- Name: COLUMN category.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.id IS '分类主键ID';


--
-- Name: COLUMN category.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.name IS '分类名称，唯一';


--
-- Name: COLUMN category.description; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.description IS '分类描述';


--
-- Name: COLUMN category.sort_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.sort_order IS '分类排序值，数值越小越靠前';


--
-- Name: COLUMN category.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.status IS '分类状态，可选值：visible、hidden';


--
-- Name: COLUMN category.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.created_at IS '分类创建时间';


--
-- Name: COLUMN category.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.category.updated_at IS '分类更新时间';


--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_config (
    id bigint NOT NULL,
    background_url character varying(500)
);


--
-- Name: site_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: TABLE tag; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tag IS '文章标签表';


--
-- Name: COLUMN tag.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tag.id IS '标签主键ID';


--
-- Name: COLUMN tag.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tag.name IS '标签名称，唯一';


--
-- Name: COLUMN tag.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tag.created_at IS '标签创建时间';


--
-- Name: COLUMN tag.updated_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tag.updated_at IS '标签更新时间';


--
-- Name: tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_like article_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_like
    ADD CONSTRAINT article_like_pkey PRIMARY KEY (id);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: article article_status_check; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.article
    ADD CONSTRAINT article_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'published'::character varying, 'hidden'::character varying])::text[]))) NOT VALID;


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: admin id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT id PRIMARY KEY (id);


--
-- Name: CONSTRAINT id ON admin; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON CONSTRAINT id ON public.admin IS '主键';


--
-- Name: site_config site_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_config
    ADD CONSTRAINT site_config_pkey PRIMARY KEY (id);


--
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- Name: article_tag uk_article_tag_article_id_tag_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT uk_article_tag_article_id_tag_id UNIQUE (article_id, tag_id);


--
-- Name: category uk_category_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk_category_name UNIQUE (name);


--
-- Name: tag uk_tag_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT uk_tag_name UNIQUE (name);


--
-- Name: idx_article_category_list_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_category_list_sort ON public.article USING btree (category_id, is_top DESC, published_at DESC NULLS LAST, created_at DESC, id DESC);


--
-- Name: idx_article_like_ip_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_like_ip_created_at ON public.article_like USING btree (ip_hash, created_at DESC);


--
-- Name: idx_article_list_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_list_sort ON public.article USING btree (is_top DESC, published_at DESC NULLS LAST, created_at DESC, id DESC);


--
-- Name: idx_article_status_list_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_status_list_sort ON public.article USING btree (status, is_top DESC, published_at DESC NULLS LAST, created_at DESC, id DESC);


--
-- Name: idx_article_summary_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_summary_trgm ON public.article USING gin (summary public.gin_trgm_ops);


--
-- Name: idx_article_tag_tag_id_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_tag_tag_id_article_id ON public.article_tag USING btree (tag_id, article_id);


--
-- Name: idx_article_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_title_trgm ON public.article USING gin (title public.gin_trgm_ops);


--
-- Name: uk_article_like_article_visitor; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_article_like_article_visitor ON public.article_like USING btree (article_id, visitor_key_hash);


--
-- Name: article_like article_like_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_like
    ADD CONSTRAINT article_like_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.article(id) ON DELETE CASCADE;


--
-- Name: article fk_article_category; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES public.category(id) ON DELETE RESTRICT;


--
-- Name: article_tag fk_article_tag_article; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES public.article(id) ON DELETE CASCADE;


--
-- Name: article_tag fk_article_tag_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES public.tag(id) ON DELETE CASCADE;


--
-- Default administrator: admin / admin
--

INSERT INTO public.admin (
    username,
    password,
    name,
    role,
    avatar,
    password_version
)
SELECT
    'admin',
    '$2a$10$Q0f61ikIU6cn47hv0wN6AuPJMhJf/RMJXJhyHJQ8Uu6kqBZ3Pgg1a',
    'admin',
    'admin',
    NULL,
    1
WHERE NOT EXISTS (
    SELECT 1
    FROM public.admin
    WHERE username = 'admin'
);


--
-- PostgreSQL database dump complete
--

\unrestrict 9WQwNmSj2qUgLjFjHk5gKJhIT4hnWGjCoFFyuC9Q7rDLhXko4VUOJFr1ItomIjQ
